const GENERATION_ACTION_TYPE = {
  FETCH_STARTED: "FETCH_GENERATION_STARTED",
  FETCH_FAILED: "FETCH_GENERATION_FAILED",
  FETCH_SUCCEEDED: "FETCH_GENERATION_SUCCEEDED"
};

const DRAGON_ACTION_TYPE = {
  FETCH_STARTED: "FETCH_DRAGON_STARTED",
  FETCH_FAILED: "FETCH_DRAGON_FAILED",
  FETCH_SUCCEEDED: "FETCH_DRAGON_SUCCEEDED"
};

const ACCOUNT_ACTION_TYPE = {
  FETCH_STARTED: "FETCH_ACCOUNT_STARTED",
  FETCH_FAILED: "FETCH_ACCOUNT_FAILED",
  LOGOUT_FETCH_SUCCEEDED: "ACCOUNT_LOGOUT_SUCCEEDED",
  LOGIN_FETCH_SUCCEEDED: "ACCOUNT_LOGIN_SUCCEEDED",
  SIGNUP_FETCH_SUCCEEDED: "ACCOUNT_SIGNUP_SUCCEEDED",
  AUTHENTICATED_FETCH_SUCCEEDED: "ACCOUNT_AUTHENTICATED_SUCCEEEDED"
};

const AccOUNT_INFO_TYPE = {
  FETCH_STARTED: "FETCH_ACCOUNT_STARTED",
  FETCH_FAILED: "FETCH_ACCOUNT_FAILED",
  FETCH_SUCCEEDED: "ACCOUNT_INFO_SUCCEEDED"
};

const ACCOUNT_DRAGONS_ACTION_TYPE = {
  FETCH_STARTED: "FETCH_ACCOUNT_DRAGON_STARTED",
  FETCH_FAILED: "FETCH_ACCOUNT_DRAGON_FAILED",
  FETCH_SUCCEEDED: "FETCH_ACCOUNT_DRAGON_SUCCEEDED"
};

const PUBLIC_DRAGONS_ACTION_TYPE = {
  FETCH_STARTED: "FETCH_PUBLIC_DRAGONS_STARTED",
  FETCH_FAILED: "FETCH_PUBLIC_DRAGONS_FAILED",
  FETCH_SUCCEEDED: "FETCH_PUBLIC_DRAGONS_SUCCEEDED"
};

export {
  GENERATION_ACTION_TYPE,
  DRAGON_ACTION_TYPE,
  ACCOUNT_ACTION_TYPE,
  ACCOUNT_DRAGONS_ACTION_TYPE,
  AccOUNT_INFO_TYPE,
  PUBLIC_DRAGONS_ACTION_TYPE
};
